package quizGenerator;

public class rules {
    rules(){
        System.out.println("== WELCOME TO THE WORLD OF QUIZ ==");
        System.out.println("HERE YOU CAN TEST YOUR LESSONS BASED ON BASIC,INTERMEDIATE,AND HARD QUESTIONS. THE RULES ARE SIMPLE");
        System.out.println("1.YOU CAN ONLY EXIT AFTER YOU GIVE A RIGHT ANSWER.");
        System.out.println("2.YOU WILL BE AUTOMATICALLY OUT OF THE GAME IF YOU GIVE WRONG ANSWER FOR FIVE TIMES IN TOTAL");
        System.out.println("3.YOU WILL HAVE THE CHANCE TO CHANGE THE QUESTION IF YOU FAIL TO ANSWER IT,MEANS IF YOU GIVE THE WRONG ANSWER.");
        System.out.println("4.BY DEFAULT YOU WILL HAVE 10 POINTS FOR EACH CORRECT ANSWER AND IF YOU TAKE HINT YOU WILL HAVE 7 POINTS FOR THE CORRECT ANSWER");
        System.out.println("5.NO POINTS WILL BE CUT FOR GIVING WRONG ANSWERS.");
        System.out.println("--->KEEP PLAYING AND KEEP ENJOYING.HAPPY QUIZZING<---");
    }
}
